# Generated by Django 4.2.16 on 2025-09-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_product_image_product_category_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.product'),
        ),
    ]
